exports.levelSequences = {
  1: ["deep", "lighthearted", "deep", "deep", "medium", "lighthearted"],
  2: [
    "lighthearted",
    "medium",
    "lighthearted",
    "medium",
    "deep",
    "lighthearted",
  ],
  3: ["medium", "lighthearted", "deep", "deep", "lighthearted", "medium"],
};

exports.levelSequences2 = {
  1: ["lighthearted",
"lighthearted",
"medium",
"medium",
"deep",
"deep",
"lighthearted",
"medium",
"medium",
"deep",
"deep",
"lighthearted",
"medium",
"lighthearted",
"medium",
"lighthearted"],
2: [
  "medium", 
"lighthearted",
"medium", 
"deep",
"deep",
"lighthearted",
"medium", 
"medium", 
"lighthearted",
"deep",
"medium", 
"medium", 
"lighthearted",
"deep",
"medium", 
"lighthearted"
],
3: [
"deep",
"lighthearted",
"medium", 
"medium", 
"deep",
"lighthearted",
"lighthearted",
"medium", 
"medium", 
"deep",
"lighthearted",
"lighthearted",
"medium", 
"lighthearted",
"deep",
"deep",
]
};

exports.levelSequences3 = {
  1: [
"lighthearted",
"lighthearted",
"lighthearted",
"medium",
"medium",
"deep",
"lighthearted",
"lighthearted",
"lighthearted",
"medium",
"deep",
"medium",
"medium",
"lighthearted",
"lighthearted",
"medium",
"medium",
"deep",
"deep",
"medium",
"lighthearted",
"lighthearted",
"lighthearted",
"medium",
"deep",
"medium",
"lighthearted",
"lighthearted",
"lighthearted",
"medium",
"deep",
"medium",
"medium",
"lighthearted",
"lighthearted",
"medium",
"medium",
"deep",
"deep",
"medium",
  ],
  2: [
"lighthearted",
"lighthearted",
"medium",
"deep",
"deep",
"medium",
"lighthearted",
"lighthearted",
"lighthearted",
"medium",
"deep",
"deep",
"medium",
"lighthearted",
"lighthearted",
"medium",
"deep",
"deep",
"deep",
"medium",
"lighthearted",
"lighthearted",
"medium",
"deep",
"deep",
"medium",
"lighthearted",
"lighthearted",
"lighthearted",
"medium",
"deep",
"deep",
"medium",
"lighthearted",
"lighthearted",
"medium",
"deep",
"deep",
"deep",
"medium",
  ]
};


exports.levelSequences4 = {
  1: [
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
  ],
  2: [
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
  ],
};