

exports.levelSequences4 = {
  1: [
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
  ],
  2: [
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: false,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "lighthearted",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: true,
      needToComeLater: true,
    },
    {
      level: "deep",
      nonNeg: false,
      needToComeLater: true,
    },
    {
      level: "medium",
      nonNeg: false,
      needToComeLater: true,
    },
  ],
};


exports.levelSequences5 = {
  1: [
    { level: "lighthearted", nonNeg: false, needToComeLater: false },
    { level: "lighthearted", nonNeg: false, needToComeLater: false },
    { level: "lighthearted", nonNeg: false, needToComeLater: false },
    { level: "medium", nonNeg: true, needToComeLater: false },
    { level: "medium", nonNeg: false, needToComeLater: false },
    { level: "deep", nonNeg: true, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: true, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
  ],
  2: [
    { level: "lighthearted", nonNeg: false, needToComeLater: false },
    { level: "medium", nonNeg: false, needToComeLater: false },
    { level: "deep", nonNeg: true, needToComeLater: false },
    { level: "deep", nonNeg: false, needToComeLater: false },
    { level: "deep", nonNeg: true, needToComeLater: false },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: true, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "lighthearted", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
    { level: "deep", nonNeg: true, needToComeLater: true },
    { level: "deep", nonNeg: false, needToComeLater: true },
    { level: "medium", nonNeg: false, needToComeLater: true },
  ],
};